[package]
name = "pikevm"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/jameysharp/pikevm/"
license = "MIT"

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
flagset = "0.4.3"
pcre2 = "0.2.3"
regex-syntax = "0.6.27"
